function p1 = auto_p1(in1,in2)
%AUTO_P1
%    P1 = AUTO_P1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Dec-2020 19:24:08

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r = in2(:,8);
p1 = [r.*(q1+q2+q3-pi);r];
