function pe = auto_pe(in1,in2)
%AUTO_PE
%    PE = AUTO_PE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Dec-2020 19:24:08

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r = in2(:,8);
t2 = q1+q2+q3;
pe = [r.*(t2-pi)-r.*sin(t2);r-r.*cos(t2)];
