function p3 = auto_p3(in1,in2)
%AUTO_P3
%    P3 = AUTO_P3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Dec-2020 19:24:08

l = in2(:,5);
lt = in2(:,7);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r = in2(:,8);
t2 = q1+q2;
p3 = [lt.*sin(q1)-l.*sin(t2)+r.*(q3+t2-pi);r+lt.*cos(q1)-l.*cos(t2)];
