function p2 = auto_p2(in1,in2)
%AUTO_P2
%    P2 = AUTO_P2(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Dec-2020 19:24:08

l = in2(:,5);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r = in2(:,8);
t2 = q1+q2;
p2 = [-l.*sin(t2)+r.*(q3+t2-pi);r-l.*cos(t2)];
