function p4 = auto_p4(in1,in2)
%AUTO_P4
%    P4 = AUTO_P4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Dec-2020 19:24:08

d = in2(:,6);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r = in2(:,8);
t2 = q1+q2;
p4 = [-d.*sin(t2)+r.*(q3+t2-pi);r-d.*cos(t2)];
