function Lfy = auto_Lfy(in1,in2)
%AUTO_LFY
%    LFY = AUTO_LFY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Dec-2020 15:36:07

d = in2(:,5);
dphi = in1(6,:);
dq1 = in1(7,:);
dq2 = in1(8,:);
r = in2(:,6);
Lfy = [dphi;(r.*(dq1+dq2))./d];
