function psi = auto_psi(in1,in2)
%AUTO_PSI
%    PSI = AUTO_PSI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Dec-2020 15:36:12

d = in2(:,5);
q1 = in1(4,:);
q2 = in1(5,:);
r = in2(:,6);
psi = (r.*(q1+q2))./d;
