function pt = auto_pt(in1,in2)
%AUTO_PT
%    PT = AUTO_PT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    20-Dec-2020 15:37:57

d = in2(:,5);
l = in2(:,4);
phi = in1(3,:);
q1 = in1(4,:);
q2 = in1(5,:);
r = in2(:,6);
x = in1(1,:);
y = in1(2,:);
t2 = sin(phi);
t3 = q1+q2;
t4 = 1.0./d;
t5 = r.*t3.*t4;
pt = [x+l.*t2.*cos(t5);y+l.*t2.*sin(t5);r+l.*cos(phi)];
